//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Res.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do it.
        /// </summary>
        internal static string Do_it {
            get {
                return ResourceManager.GetString("Do it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Exam not found!.
        /// </summary>
        internal static string Entity_Exam_not_found_ {
            get {
                return ResourceManager.GetString("Entity Exam not found!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Result not found!.
        /// </summary>
        internal static string Entity_Result_not_found_ {
            get {
                return ResourceManager.GetString("Entity Result not found!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred!.
        /// </summary>
        internal static string ERROR_OCCURRED {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam has been already closed!.
        /// </summary>
        internal static string EXAM_CLOSED {
            get {
                return ResourceManager.GetString("EXAM_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam not start!.
        /// </summary>
        internal static string EXAM_NOT_START {
            get {
                return ResourceManager.GetString("EXAM_NOT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSize exceed, at most 5 M.
        /// </summary>
        internal static string FileSize_exceed__at_most_5_M {
            get {
                return ResourceManager.GetString("FileSize exceed, at most 5 M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password can not be empty!.
        /// </summary>
        internal static string INPUT_NOT_EMPTY {
            get {
                return ResourceManager.GetString("INPUT_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input valid number.
        /// </summary>
        internal static string INPUT_NOT_NUM {
            get {
                return ResourceManager.GetString("INPUT_NOT_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert current answerStr fail.
        /// </summary>
        internal static string Insert_current_answerStr_fail {
            get {
                return ResourceManager.GetString("Insert current answerStr fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert exam result fail.
        /// </summary>
        internal static string Insert_exam_result_fail {
            get {
                return ResourceManager.GetString("Insert exam result fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File!.
        /// </summary>
        internal static string Invalid_File_ {
            get {
                return ResourceManager.GetString("Invalid File!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score is {0} points, you got {1} questions in this test..
        /// </summary>
        internal static string lblExamStrResult_Text {
            get {
                return ResourceManager.GetString("lblExamStrResult.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login password is incorrect.
        /// </summary>
        internal static string Login_password_is_incorrect {
            get {
                return ResourceManager.GetString("Login password is incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  min.
        /// </summary>
        internal static string MIN_UNIT {
            get {
                return ResourceManager.GetString("MIN_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a answer!.
        /// </summary>
        internal static string NO_CHOOSE_ANSWER {
            get {
                return ResourceManager.GetString("NO_CHOOSE_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pass.
        /// </summary>
        internal static string No_Pass {
            get {
                return ResourceManager.GetString("No Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record On This Condition!.
        /// </summary>
        internal static string No_Record_On_This_Condition_ {
            get {
                return ResourceManager.GetString("No Record On This Condition!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a picture!.
        /// </summary>
        internal static string Not_a_picture_ {
            get {
                return ResourceManager.GetString("Not a picture!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Attend.
        /// </summary>
        internal static string Not_Attend {
            get {
                return ResourceManager.GetString("Not Attend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query question list fail.
        /// </summary>
        internal static string Query_question_list_fail {
            get {
                return ResourceManager.GetString("Query question list fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user avatar successfully.
        /// </summary>
        internal static string SET_USER_ICON_SUC {
            get {
                return ResourceManager.GetString("SET_USER_ICON_SUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be less than end time.
        /// </summary>
        internal static string TIME_START_BEFORE_END {
            get {
                return ResourceManager.GetString("TIME_START_BEFORE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at .
        /// </summary>
        internal static string TIP_AT {
            get {
                return ResourceManager.GetString("TIP_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Please attend the.
        /// </summary>
        internal static string TIP_ATTEND {
            get {
                return ResourceManager.GetString("TIP_ATTEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} questions correct..
        /// </summary>
        internal static string TIP_CURRECT_QUESTION {
            get {
                return ResourceManager.GetString("TIP_CURRECT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  exam result.
        /// </summary>
        internal static string TIP_EXAM_RESULT {
            get {
                return ResourceManager.GetString("TIP_EXAM_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  exam on .
        /// </summary>
        internal static string TIP_TIME {
            get {
                return ResourceManager.GetString("TIP_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the keyword.
        /// </summary>
        internal static string txtName_Text {
            get {
                return ResourceManager.GetString("txtName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string txtPassword_Text {
            get {
                return ResourceManager.GetString("txtPassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string txtUsername_Text {
            get {
                return ResourceManager.GetString("txtUsername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username does not exist.
        /// </summary>
        internal static string Username_does_not_exist {
            get {
                return ResourceManager.GetString("Username does not exist", resourceCulture);
            }
        }
    }
}
