//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.FileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.IFileService")]
    public interface IFileService {
        
        // CODEGEN: Generating message contract since the wrapper name (FileUploadData) of message FileUploadData does not match the default value (UploadFile)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFileService/UploadFile")]
        void UploadFile(UI.FileService.FileUploadData request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IFileService/UploadFile")]
        System.IAsyncResult BeginUploadFile(UI.FileService.FileUploadData request, System.AsyncCallback callback, object asyncState);
        
        void EndUploadFile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetUploadFileInfo", ReplyAction="http://tempuri.org/IFileService/GetUploadFileInfoResponse")]
        int GetUploadFileInfo(string id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFileService/GetUploadFileInfo", ReplyAction="http://tempuri.org/IFileService/GetUploadFileInfoResponse")]
        System.IAsyncResult BeginGetUploadFileInfo(string id, System.AsyncCallback callback, object asyncState);
        
        int EndGetUploadFileInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileService/GetUserIcon", ReplyAction="http://tempuri.org/IFileService/GetUserIconResponse")]
        System.Drawing.Bitmap GetUserIcon(int userId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFileService/GetUserIcon", ReplyAction="http://tempuri.org/IFileService/GetUserIconResponse")]
        System.IAsyncResult BeginGetUserIcon(int userId, System.AsyncCallback callback, object asyncState);
        
        System.Drawing.Bitmap EndGetUserIcon(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadData {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int FileSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileUniqueID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileData;
        
        public FileUploadData() {
        }
        
        public FileUploadData(string FileName, int FileSize, string FileUniqueID, int UserId, System.IO.Stream FileData) {
            this.FileName = FileName;
            this.FileSize = FileSize;
            this.FileUniqueID = FileUniqueID;
            this.UserId = UserId;
            this.FileData = FileData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServiceChannel : UI.FileService.IFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUploadFileInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUploadFileInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserIconCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserIconCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Drawing.Bitmap Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Drawing.Bitmap)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceClient : System.ServiceModel.ClientBase<UI.FileService.IFileService>, UI.FileService.IFileService {
        
        private BeginOperationDelegate onBeginUploadFileDelegate;
        
        private EndOperationDelegate onEndUploadFileDelegate;
        
        private System.Threading.SendOrPostCallback onUploadFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUploadFileInfoDelegate;
        
        private EndOperationDelegate onEndGetUploadFileInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetUploadFileInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserIconDelegate;
        
        private EndOperationDelegate onEndGetUserIconDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserIconCompletedDelegate;
        
        public FileServiceClient() {
        }
        
        public FileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UploadFileCompleted;
        
        public event System.EventHandler<GetUploadFileInfoCompletedEventArgs> GetUploadFileInfoCompleted;
        
        public event System.EventHandler<GetUserIconCompletedEventArgs> GetUserIconCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void UI.FileService.IFileService.UploadFile(UI.FileService.FileUploadData request) {
            base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string FileName, int FileSize, string FileUniqueID, int UserId, System.IO.Stream FileData) {
            UI.FileService.FileUploadData inValue = new UI.FileService.FileUploadData();
            inValue.FileName = FileName;
            inValue.FileSize = FileSize;
            inValue.FileUniqueID = FileUniqueID;
            inValue.UserId = UserId;
            inValue.FileData = FileData;
            ((UI.FileService.IFileService)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI.FileService.IFileService.BeginUploadFile(UI.FileService.FileUploadData request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUploadFile(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUploadFile(string FileName, int FileSize, string FileUniqueID, int UserId, System.IO.Stream FileData, System.AsyncCallback callback, object asyncState) {
            UI.FileService.FileUploadData inValue = new UI.FileService.FileUploadData();
            inValue.FileName = FileName;
            inValue.FileSize = FileSize;
            inValue.FileUniqueID = FileUniqueID;
            inValue.UserId = UserId;
            inValue.FileData = FileData;
            return ((UI.FileService.IFileService)(this)).BeginUploadFile(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndUploadFile(System.IAsyncResult result) {
            base.Channel.EndUploadFile(result);
        }
        
        private System.IAsyncResult OnBeginUploadFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string FileName = ((string)(inValues[0]));
            int FileSize = ((int)(inValues[1]));
            string FileUniqueID = ((string)(inValues[2]));
            int UserId = ((int)(inValues[3]));
            System.IO.Stream FileData = ((System.IO.Stream)(inValues[4]));
            return this.BeginUploadFile(FileName, FileSize, FileUniqueID, UserId, FileData, callback, asyncState);
        }
        
        private object[] OnEndUploadFile(System.IAsyncResult result) {
            this.EndUploadFile(result);
            return null;
        }
        
        private void OnUploadFileCompleted(object state) {
            if ((this.UploadFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadFileAsync(string FileName, int FileSize, string FileUniqueID, int UserId, System.IO.Stream FileData) {
            this.UploadFileAsync(FileName, FileSize, FileUniqueID, UserId, FileData, null);
        }
        
        public void UploadFileAsync(string FileName, int FileSize, string FileUniqueID, int UserId, System.IO.Stream FileData, object userState) {
            if ((this.onBeginUploadFileDelegate == null)) {
                this.onBeginUploadFileDelegate = new BeginOperationDelegate(this.OnBeginUploadFile);
            }
            if ((this.onEndUploadFileDelegate == null)) {
                this.onEndUploadFileDelegate = new EndOperationDelegate(this.OnEndUploadFile);
            }
            if ((this.onUploadFileCompletedDelegate == null)) {
                this.onUploadFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadFileCompleted);
            }
            base.InvokeAsync(this.onBeginUploadFileDelegate, new object[] {
                        FileName,
                        FileSize,
                        FileUniqueID,
                        UserId,
                        FileData}, this.onEndUploadFileDelegate, this.onUploadFileCompletedDelegate, userState);
        }
        
        public int GetUploadFileInfo(string id) {
            return base.Channel.GetUploadFileInfo(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUploadFileInfo(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUploadFileInfo(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndGetUploadFileInfo(System.IAsyncResult result) {
            return base.Channel.EndGetUploadFileInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetUploadFileInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return this.BeginGetUploadFileInfo(id, callback, asyncState);
        }
        
        private object[] OnEndGetUploadFileInfo(System.IAsyncResult result) {
            int retVal = this.EndGetUploadFileInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUploadFileInfoCompleted(object state) {
            if ((this.GetUploadFileInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUploadFileInfoCompleted(this, new GetUploadFileInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUploadFileInfoAsync(string id) {
            this.GetUploadFileInfoAsync(id, null);
        }
        
        public void GetUploadFileInfoAsync(string id, object userState) {
            if ((this.onBeginGetUploadFileInfoDelegate == null)) {
                this.onBeginGetUploadFileInfoDelegate = new BeginOperationDelegate(this.OnBeginGetUploadFileInfo);
            }
            if ((this.onEndGetUploadFileInfoDelegate == null)) {
                this.onEndGetUploadFileInfoDelegate = new EndOperationDelegate(this.OnEndGetUploadFileInfo);
            }
            if ((this.onGetUploadFileInfoCompletedDelegate == null)) {
                this.onGetUploadFileInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUploadFileInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetUploadFileInfoDelegate, new object[] {
                        id}, this.onEndGetUploadFileInfoDelegate, this.onGetUploadFileInfoCompletedDelegate, userState);
        }
        
        public System.Drawing.Bitmap GetUserIcon(int userId) {
            return base.Channel.GetUserIcon(userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUserIcon(int userId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserIcon(userId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Drawing.Bitmap EndGetUserIcon(System.IAsyncResult result) {
            return base.Channel.EndGetUserIcon(result);
        }
        
        private System.IAsyncResult OnBeginGetUserIcon(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userId = ((int)(inValues[0]));
            return this.BeginGetUserIcon(userId, callback, asyncState);
        }
        
        private object[] OnEndGetUserIcon(System.IAsyncResult result) {
            System.Drawing.Bitmap retVal = this.EndGetUserIcon(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserIconCompleted(object state) {
            if ((this.GetUserIconCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserIconCompleted(this, new GetUserIconCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserIconAsync(int userId) {
            this.GetUserIconAsync(userId, null);
        }
        
        public void GetUserIconAsync(int userId, object userState) {
            if ((this.onBeginGetUserIconDelegate == null)) {
                this.onBeginGetUserIconDelegate = new BeginOperationDelegate(this.OnBeginGetUserIcon);
            }
            if ((this.onEndGetUserIconDelegate == null)) {
                this.onEndGetUserIconDelegate = new EndOperationDelegate(this.OnEndGetUserIcon);
            }
            if ((this.onGetUserIconCompletedDelegate == null)) {
                this.onGetUserIconCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserIconCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserIconDelegate, new object[] {
                        userId}, this.onEndGetUserIconDelegate, this.onGetUserIconCompletedDelegate, userState);
        }
    }
}
